name: validate-craq
on:
  push:
env:
  NODE_VERSION: 14

jobs:
  test-craq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Requirements
        working-directory: services/craq
        run: |
          yarn install --frozen-lockfile

      - name: Run Linting
        working-directory: services/craq
        run: |
          yarn lint

      - name: Run Tests
        working-directory: services/craq
        run: |
          yarn test_xml

      - name: Create test report
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: CRAQ Validation Tests
          files: services/craq/testresults.xml
